version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9003:9000"
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERCONNECT: redpanda:9092